### ISSUE TITLE
抽象成可以支持不同平台扩展的

### ISSUE THREAD

**Issue by xiaohuoni** [anye931123/react-visual-editor#1]
把主要的东西抽象一下。
把数据传入和渲染哪部分的东西暴露出来。
交给其他人去实现和使用。
比如，我需要一个移动端版本的，我需要fork这个库，然后修改。
我期望的是，能在另一个库引入 @react-visual-editor/core。
然后感觉也可以取一个项目别名，现在的三单词太长了，交流的时候不太方便。

**Comment by anye931123** [comment]
嗯，后期我再抽离核心模块拆分

**Comment by lzm0x219** [comment]
是不是脉脉那个？

**Comment by puti94** [comment]
这个需求+1，之前想法就是想自动拖拽生成react-native页面，服务端保存页面json,app请求页面数据就可以动态渲染了。

**Comment by anye931123** [comment]
最近开始准备抽核心，项目数据结构会优化，整体性能优化提升

**Comment by JoeImJoe** [comment]
react-native需求加一

**Comment by anye931123** [comment]
已抽取，分支brickd
