### ISSUE TITLE
保存模板可以生成本地版么？

### ISSUE THREAD

**Issue by pxim** [anye931123/react-visual-editor#14]
大佬，保存模板可以生成本地版么？
然后支持导入和导出，比如我导出一个模板，别人可以导入模板。

**Comment by anye931123** [comment]
你说的是代码还是功能中的模板，功能中的模板，是可以的支持 导入与导出，代码的话理论上也是可以的不过目前没实现

**Comment by pxim** [comment]
> 你说的是代码还是功能中的模板，功能中的模板，是可以的支持 导入与导出，代码的话理论上也是可以的不过目前没实现

![image](https://user-images.githubusercontent.com/5111701/84097720-e7f90000-aa37-11ea-9a79-15ac4eb3d8b9.png)
https://brick-design.github.io/react-visual-editor/ 用的这个地址上的demo
这个模板，目前没有找到导出的触发按钮，
并且，这个模板是昨天生成的，今天没办法使用了，不管是双击，还是拓展都不在中间的显示区域显示；

**Comment by anye931123** [comment]
你需要拖拽添加，生成的模板也属于组件类支持拖拽，你可以从模板列表中拖拽你想要添加的模板到设计面板中指定的容器组件中，demo中使用了indexDB模拟的后台CRUD,可以将indexDB的实现替换成真实的后台CRUD.
