### ISSUE TITLE
拖动子级元素到页面时报错问题.

### ISSUE THREAD

**Issue by oc-Design** [anye931123/react-visual-editor#16]
1.当非子元素拖动到页面时,会给警报示例如:Menu.SubMenu:Only allowed as a child node or attribute node ofMenu.children,Menu.ItemGroup.children,Item,Menu.SubMenu.children.然后报错:TypeError: Cannot read property '0' of undefined
2.Anchor/select/collapse/menu/treeselect这几个元素子元素拖动到页面时就报错::TypeError: Cannot read property '0' of undefined,但是拖动到右侧组件树不报错
3.drapdown拖动到页面时其他元素不显示

**Comment by anye931123** [comment]
已修复
