### ISSUE TITLE
性能很差，chrome 都很吃力，16G的内存的Mac，chrome 都停止响应

### ISSUE THREAD

**Issue by Ca1ifornia** [anye931123/react-visual-editor#2]

**Comment by anye931123** [comment]
你试试class版代码，Hook版最近才重构完，我正在优化

**Comment by anye931123** [comment]
如果你是在线预览看不了，那是因为网络问题，在线预览我托管在github pages上网络不好加载很慢的

**Comment by Ca1ifornia** [comment]
不是在线预览，就是简单拖拽，比如增加一个menu，就开始变迟钝了，看了一下进程 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/25984964/76179696-bb460a00-61f6-11ea-9e9b-5bfed792dcb6.png">

**Comment by anye931123** [comment]
进群交流一下

**Comment by Ca1ifornia** [comment]
行吧，哪个比较常用，微信还是qq

**Comment by anye931123** [comment]
微信，我查到了是bug Hook版有bug，我最近才从class重构Hook，代码改动太大，出bug了

**Comment by anye931123** [comment]
menu类组件是有约束要求的，antd menu的二级组件依赖于Menu的Context，如果放入其他组件就找不到Menu Context就会崩溃。menu类组件已添加父组件约束，你可以验证一下。

**Comment by Ca1ifornia** [comment]
我就往里面的title放入一个span 放不进去

**Comment by anye931123** [comment]
已解决
