### ISSUE TITLE
官网运行的版本与本地运行的版本不一致问题

### ISSUE THREAD

**Issue by ctq123** [anye931123/react-visual-editor#32]
官网https://brick-design.github.io/react-visual-editor/

我们本地通过 yarn dev:example运行的版本与上面的不一样，请问官网运行的版本是哪个版本？

![image](https://user-images.githubusercontent.com/12124169/106725301-2fc23c80-6644-11eb-90f4-24558ca120dc.png)
官网（如上图）

![image](https://user-images.githubusercontent.com/12124169/106725344-3b156800-6644-11eb-9b0c-7a33e68e516a.png)
本地（如上图）

**Comment by ctq123** [comment]
官网的预览是正常的，本地的预览是不正常的

**Comment by erdong-fe** [comment]
release是umi block的是在线版本的源码
