### ISSUE TITLE
先执行以下 npm run build

### ISSUE THREAD

**Issue by cy-98** [anye931123/react-visual-editor#33]
先执行以下 npm run build

_Originally posted by @anye931123 in https://github.com/brick-design/react-visual-editor/issues/31#issuecomment-757949601_

还是会编译报错，react-dom的type重复声明，为啥会出现这个错误呢

**Comment by cy-98** [comment]
TypeScript error in /Users/admin/Desktop/react-visual-editor/examples/react-example/node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2985,14):
Duplicate identifier 'LibraryManagedAttributes'.  TS2300

    2983 |         // We can't recurse forever because `type` can't be self-referential;
    2984 |         // let's assume it's reasonable to do a single React.lazy() around a single React.memo() / vice-versa
  > 2985 |         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
         |              ^
    2986 |             ? T extends React.MemoExoticComponent<infer U> | React.LazyExoticComponent<infer U>
    2987 |                 ? ReactManagedAttributes<U, P>
    2988 |                 : ReactManagedAttributes<T, P>

**Comment by cy-98** [comment]
貌似需要溢出package.json的@types/react-dom 再重新安装@types/react  @types/react-dom

**Comment by anye931123** [comment]
初始项目必须使用yarn install初始化
