### ISSUE TITLE
block方式添加到ant design Pro中报错

### ISSUE THREAD

**Issue by mushroomlb** [anye931123/react-visual-editor#4]
如下图所示，在使用umi block add https://github.com/anye931123/react-visual-editor 方式添加到ant design Pro中报错：
![image](https://user-images.githubusercontent.com/1701771/77140579-0395df80-6ab5-11ea-9d0b-b335c40a9988.png)

系统：ubuntu
npm版本：6.13.2

**Comment by anye931123** [comment]
目前的是基于umi 2的版本，antd 3的版本

**Comment by mushroomlb** [comment]
嗯，看到了，是版本冲突，有升级计划吗

**Comment by anye931123** [comment]
我暂时没时间，你可以自己尝试一下，直接将src中的文件完全拷贝到你的项目的pages中建的页面(文件夹中)，将package中的依赖拷贝到你的项目的package中，需要将@文件路径修改一下。我用的一些antd3 的组件如果有冲突修改一下，好像antd4 form用法有修改。应该就可以了
