### ISSUE TITLE
很赞，支持一波

### ISSUE THREAD

**Issue by huangshuwei** [anye931123/react-visual-editor#5]
让我想到我们2018年用vuejs做的项目。当初我们的目标是通过这个项目可以让产品人员自己拖拽生成自己想要的页面，支持发布并导出项目代码，从而开发人员只需填写业务逻辑。中间直接可以省去美工切图和写样式。当时我们已经支持到：
1、移动端、PC 端拖拽配置
2、组件库配置化方式，即可以切换组件库（主要是部门自己的组件库和element-ui）
3、项目模板功能
4、组件模板功能
5、导出项目。代码方式，和本项目很类似
6、版本管理。对产品变更需求的管理（文档+代码）
7、实时预览
等...

发布多个版本后，产品人员也开始配置项目了，从而问题也暴露出来。产品的需求变化多样（抄袭市场不同的设计），导致一套组件库很难满足他们的需求。当新版本准备支持 react 时，决定放弃了这个项目。

说那么多，实际想表达，如果是当做技术锻炼，我觉得很赞，实现了很多功能。如果项目想要推广出去让更多的用户使用，你要考虑是否能满足用户的需求。

不管怎么样，支持一波

**Comment by huangshuwei** [comment]
当初做的移动端配置工具截图
![image](https://user-images.githubusercontent.com/6047141/77717928-93d7a580-701c-11ea-85a0-67a3ba3cb818.png)

**Comment by anye931123** [comment]
谢谢支持，加个好友交流交流

**Comment by DoublePoint** [comment]
工具类的产品除非有很强的资金支持，或者社区支持，否则步履维艰，希望作者加油

**Comment by cnAlexJiang** [comment]
> 谢谢支持，加个好友交流交流

请问这个是个人项目还是团队项目
如果是团队项目  团队还缺人吗

**Comment by kinsliy** [comment]
不同的设计确实很麻烦，感觉还是像B端可能更好一些，但B端的话，又不需要怎么拖拽了，直接写可能更快
