### ISSUE TITLE
安装@brickd/react模块报错

### ISSUE THREAD

**Issue by little-yaonv** [anye931123/react-visual-editor#75]
大佬，请问安装@brickd/react模块的时候，总是报错：找不到@brick/utils，请问怎么解决
![image](https://github.com/brick-design/brick-design/assets/75791730/354bbc72-21ba-45d3-9bdc-6597884bdbfb)

**Comment by anye931123** [comment]
请使用yarn 命令，项目使用yarn workspace 功能

**Comment by little-yaonv** [comment]
好嘞，谢谢大佬
